server:
  port: 8083

spring:
  application:
    name: simulation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sailboats_simulation
    username: sailboats
    password: sailboats
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info
